---
title: "GETS_latex_test"
format: pdf
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| results: hide
#| message: false
#| warning: false


# browseVignettes("gets")

# GETS: Genral to spesific modeling and indicator saturation method

#' arx(): ar-x with the log arch-x error
#' getsm(): gets modeling of the mean specificatio of an arx  
#' getsv(): gets of the log-variance specification of an arx
#' isat(): 
#' 
#' Backward elimination of single and mulitple hypotesis testing., goodness to fit and diagnose tests

# GETS: automated genral to specific modeling and IS

#Campos J, Hendry DF, Ericsson NR (eds.) (2005). General-to-Specific Modeling. Volumes 1 and 2. Edward Elgar Publishing, Cheltenham.

# The main model class under con- sideration is the autoregressive (AR) model with exponential autoregressive conditional het-eroscedastic (ARCH) variance,

# LDGP (Hendry and Doornik, 2014)

# y = BX
# Bi is relevant if B != 0, 
# GETS: Try to find as many as possible variable that corresponds to a signifiancant level ALFA

# Backwards elimintaion, test on the B, diagnose mm.

# Tree steps
#1) Formualte GUM: Genreal unrestricetde model -- passes a set of chosen dignostics test
# A regressior is non significant if t-test (two-sided) is lower than the chosen signif. level alfa

# 2) Undertake the backwards elimination along multiple paths. This by
# removing one-by-one non-significant regressors.
# Each removal is checked for validy aginst the chosen set of diagnositc test, and
# and for parsimonious encompassing against the GUM

# 3) Select among the terminal models, the spesification with the best fit according to fit-criterion (information criterion)

# For k candidate variables, there are 2^k possible models.
# as k-beckome large, the number become computtationally infeasible. A structural search is therefore done by the GETS, 
# removing variables along a seasch path while checking the diagnostics at each removal.


# Alternatives to gets: stas (core Team) -- search for the best AR(P), using AIC.
# step (stats) both forward -- backward steps-wise seach. Lars (Hastie and Efron, 2013) and glmnet (Friedman)
# shrinkage based searh methods


# Example -----------------------------------------------------------------

library(lgarch)

set.seed(123)

y <- arima.sim( list( ar = 0.4), 100)

eps <- lgarchSim(100, arch = 0.3, garch = 0)


yy <- arima.sim( list(ar = 0.4), 100, innov = eps)

plot(as.zoo(cbind(y,yy,eps)), screens = 1)


## GETS
library(gets)

mod01 <- arx(y, ar = 1)

# Two diagnostic test are of standardized residuals z.
# AR and ARCH test are Ljung and Box (1978) test for serial correlation in z and z2

# mc = mean constant -- include a constant
# ar = ar = 1, ar = c(2,4), 1:4 osv
# mxreg: attitional regresors
# vcov.type: "ordinary" white (hetrocedasticity and autocrorrelation robust variance covariance matric) Newey and West (1987)

mX <- matrix( rnorm(100*5), 100, 5)

model02 <- arx(y, ar = 1:2, mxreg = mX, vcov.type = "white")
```



```{r}
#| echo: false
#| results: asis
#| message: false
#| warning: false



cat( toLatex(model02))
```

